### model
model_name_or_path: WeijianQi1999/Qwen25-1p5B-Memory
trust_remote_code: true
skip_embed_head: false

### method
stage: sft
do_train: true
finetuning_type: freeze_llm_for_memory

### dataset
dataset: collected_stage1_data_webshop_qwen2.5-1.5b-trial_train
eval_dataset: collected_stage1_data_webshop_qwen2.5-1.5b-trial_val
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
has_memory: true

### output
output_dir: saves/qwen25-1p5b-memory/stage_1_sft_qwen2.5-1.5b-instruct-trial
logging_steps: 5
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 32
learning_rate: 1e-3
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true

### eval
val_size: 0.0
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 40

### wandb
wandb_project: webshop_sft_using_llamafactory