### model
model_name_or_path: saves/qwen25-1p5b-memory/freeze_llm_for_memory/stage_1_sft/checkpoint-300_converted
trust_remote_code: true
skip_embed_head: false

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: webshop_train_keep_action_with_cm_policy_only
eval_dataset: webshop_val_keep_action_with_cm_policy_only
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
has_memory: true

### output
output_dir: saves/qwen25-1p5b-memory/stage_2_sft
logging_steps: 5
save_steps: 40
plot_loss: true
overwrite_output_dir: true
save_only_model: false
### train
per_device_train_batch_size: 8  # Can try 12-16 per GPU with FSDP on A100-40GB
gradient_accumulation_steps: 32  # Can reduce if you increase batch size
learning_rate: 1e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
pure_bf16: true
# Gradient checkpointing: Trade compute for memory (CRITICAL for memory savings)
gradient_checkpointing: true

# DeepSpeed ZeRO-2 configuration (stable for multi-GPU)
deepspeed: examples/deepspeed/ds_z2_config.json
flash_attn: fa2

### eval
val_size: 0.0
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 40

### wandb
wandb_project: webshop_sft_using_llamafactory
