### model
model_name_or_path: /fs/ess/PAS1576/qwjian/agent-memory-lab/hf_models/Qwen3_memory_8B_instruct
trust_remote_code: true
is_memory_model: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: new_webshop_hard_coded_obs_train
eval_dataset: new_webshop_hard_coded_obs_val
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
has_memory: true

### output
output_dir: saves/qwen3_8b-memory
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 1e-6
memory_lr: 1e-3
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
max_grad_norm: 1.0
bf16: true
# Enable DDP for 2-GPU data parallel training
ddp_find_unused_parameters: false
ddp_backend: nccl

### eval
val_size: 0.0
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 40

### wandb
wandb_project: webshop_sft_using_llamafactory_new
report_to: none